[package]
name = "openrelay_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "openrelay_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = "0.10.3"
thiserror = "2.0.12"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true